# Generated by Django 2.2.5 on 2021-03-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210315_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
